### ISSUE TITLE
tuxedo-backlight-control does not start

### ISSUE THREAD

**Issue by xevilstar** [tuxedocomputers/tuxedo-keyboard#121]
root@ghost:~# python -V
Python 3.9.10
root@ghost:~# /usr/share/tuxedo-backlight-control/ui.py
Traceback (most recent call last):
  File "/usr/share/tuxedo-backlight-control/ui.py", line 358, in <module>
    init()
  File "/usr/share/tuxedo-backlight-control/ui.py", line 353, in init
    App(root)
  File "/usr/share/tuxedo-backlight-control/ui.py", line 51, in __init__
    'color_left': tk.StringVar(self, value=backlight.color_left.capitalize()),
AttributeError: 'NoneType' object has no attribute 'capitalize'

**Comment by vinzv** [comment]
You're messing up tuxedo-backlight-control with tuxedo-keyboard. The earlier it's not from us. For issues with tuxedo-backlight-control please ask here: https://github.com/webketje/tuxedo-backlight-control

**Comment by xevilstar** [comment]
https://github.com/webketje/tuxedo-backlight-control/issues/20
