### ISSUE TITLE
Can't use backlight control on tongfeng laptop

### ISSUE THREAD

**Issue by maierjeff** [tuxedocomputers/tuxedo-keyboard#65]
Hey I have a tongfang laptop from a brazilian manufacturer, It is similar as the polaris model, and even is called Polaris too, and the model is gk5np50.

I've installed POP Os on it, and I can run tuxedo control center, but when I did it, it freezes my keyboardbacklight, so I downloaded this control, but when I will start the gui, i receive it: 

j3ff@pop-os:~$ backlight ui
Traceback (most recent call last):
  File "/usr/local/bin/backlight", line 36, in <module>
    init()
  File "/usr/share/tuxedo-backlight-control/ui.py", line 344, in init
    App(root)
  File "/usr/share/tuxedo-backlight-control/ui.py", line 58, in __init__
    initial_mode = backlight.mode.capitalize()
AttributeError: 'NoneType' object has no attribute 'capitalize'

**Comment by maierjeff** [comment]
> Hey I have a tongfang laptop from a brazilian manufacturer, It is similar as the polaris model, and even is called Polaris too, and the model is gk5np50.
> 
> I've installed POP Os on it, and I can run tuxedo control center, but when I did it, it freezes my keyboardbacklight, so I downloaded this control, but when I will start the gui, i receive it:
> 
> j3ff@pop-os:~$ backlight ui
> Traceback (most recent call last):
> File "/usr/local/bin/backlight", line 36, in
> init()
> File "/usr/share/tuxedo-backlight-control/ui.py", line 344, in init
> App(root)
> File "/usr/share/tuxedo-backlight-control/ui.py", line 58, in **init**
> initial_mode = backlight.mode.capitalize()
> AttributeError: 'NoneType' object has no attribute 'capitalize'

edit: Wrong place to post it
